name: Fetch Google Flights Data

on:
  schedule:
    - cron: "0 0,4,8,12,16,20 * * *" # 6 esecuzioni al giorno
  workflow_dispatch:  # Permette esecuzione manuale

jobs:
  fetch-flights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas gspread oauth2client serpapi google-search-results

      - name: Run flight search script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          sleep_time=$(( RANDOM % 3600 ))  # Max 60 min di ritardo
          echo "Waiting for $sleep_time seconds before execution..."
          sleep $sleep_time
          python call_api.py